# Generated by Django 6.0 on 2025-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mfacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('other', 'Other')], default='haircut', max_length=20),
        ),
    ]
