# Generated by Django 6.0 on 2025-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicerequest_notes_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
