# Generated by Django 6.0 on 2025-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('provider', 'Provider'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payout_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_confirmed_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_confirmed_completion',
            field=models.BooleanField(default=False),
        ),
    ]
