# Generated by Django 6.0 on 2025-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_membershipcounter_customuser_age_at_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
