# Generated by Django 6.0 on 2025-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
