# Generated by Django 6.0 on 2025-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_city_name_customuser_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
