# Generated by Django 6.0 on 2025-12-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servicerequest_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/ids/back/%Y/%m/%d/', verbose_name='ID Back'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='id_document_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification/ids/front/%Y/%m/%d/', verbose_name='ID Front'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Provider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verification/selfies/%Y/%m/%d/', verbose_name='Selfie with ID'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_provider', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='core.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
