# Generated by Django 6.0 on 2025-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_serviceprovider_id_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency_source',
            field=models.CharField(choices=[('signup', 'Signup Country'), ('gps', 'GPS Location'), ('manual', 'Manual Selection')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_currency_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_known_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_known_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (USD, EUR, GHS, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency used for this booking', max_length=3),
        ),
    ]
