# Generated by Django 6.0 on 2025-12-21 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_servicerequest_status_stripepaymentintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offered', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='core.serviceprovider')),
            ],
            options={
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
