# Generated by Django 6.0 on 2025-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_serviceproviderpricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='price_per_km',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='serviceproviderpricing',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('nails', 'Nail Art'), ('makeup', 'Makeup'), ('facial', 'Facial'), ('waxing', 'Waxing'), ('massage', 'Massage'), ('styling', 'Hair Styling'), ('treatment', 'Hair Treatment'), ('extensions', 'Hair Extensions'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('nails', 'Nail Art'), ('makeup', 'Makeup'), ('facial', 'Facial'), ('waxing', 'Waxing'), ('massage', 'Massage'), ('styling', 'Hair Styling'), ('treatment', 'Hair Treatment'), ('extensions', 'Hair Extensions'), ('other', 'Other')], default='haircut', max_length=20),
        ),
    ]
