# Generated by Django 6.0 on 2025-12-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_providerportfoliopost_providerportfoliomedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('suggestions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
