# Generated by Django 6.0 on 2025-12-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_accountdeletionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', help_text='BCP-47 language code, e.g. en, fr, es, pt-BR', max_length=20),
        ),
    ]
