# Generated by Django 6.0 on 2026-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='no_providers_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='providers_available_notified',
            field=models.BooleanField(default=False),
        ),
    ]
