# Generated by Django 6.0 on 2026-01-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_servicerequest_no_providers_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', help_text='Stripe connected account id (acct_...)', max_length=64),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='platform_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_earnings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provider share before Stripe processing fee (85% of total paid).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Provider net after Stripe fee deduction (provider_earnings_amount - stripe_fee_amount).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_balance_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stripe processing fee for the payment (will be deducted from provider share).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
