# Generated by Django 6.0 on 2026-01-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_serviceprovider_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_tip_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional tip amount left by the requester.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='unpaid', max_length=20),
        ),
    ]
