# Generated by Django 6.0 on 2026-01-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_wallet_models_and_servicerequest_wallet_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerwallet',
            new_name='core_provid_provide_a2b647_idx',
            old_name='core_provid_provider_8a15d6_idx',
        ),
        migrations.RenameIndex(
            model_name='walletledgerentry',
            new_name='core_wallet_status_2c1673_idx',
            old_name='core_walletl_status_8f61f2_idx',
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['wallet', 'created_at'], name='core_wallet_wallet__764850_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['kind'], name='core_wallet_kind_e05276_idx'),
        ),
    ]
