# Generated by Django 6.0 on 2026-01-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_provider_payout_settings'),
        ('core', '0031_rename_core_provid_provider_8a15d6_idx_core_provid_provide_a2b647_idx_and_more'),
    ]

    operations = [
    ]
