# Generated by Django 6.0 on 2026-01-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20260105_1657'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerpayoutsettings',
            new_name='core_provid_auto_pa_ef9e9c_idx',
            old_name='core_payout_auto_weekday_idx',
        ),
    ]
