# Generated by Django 6.0 on 2026-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_flutterwave_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='flutterwave_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='payout',
            name='flutterwave_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payout',
            name='flutterwave_transfer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_bank_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_beneficiary_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='payout_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('flutterwave', 'Flutterwave')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
