# Generated by Django 6.0 on 2026-01-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_payout_flutterwave_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
