# Generated by Django 6.0 on 2026-01-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_servicerequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_country_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
