# Generated by Django 6.0 on 2026-01-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_providerpayoutsettings_flutterwave_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='tip_flutterwave_transaction_id',
            field=models.CharField(blank=True, help_text='Flutterwave transaction ID for tip payment.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_flutterwave_tx_ref',
            field=models.CharField(blank=True, help_text='Flutterwave transaction reference for tip payment.', max_length=120, null=True),
        ),
    ]
