# Generated by Django 6.0 on 2026-01-12 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_servicerequest_tip_flutterwave_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.ForeignKey(blank=True, help_text='The booking this review is for (optional for legacy reviews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.servicerequest'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'service_request')},
        ),
    ]
