# Generated by Django 6.0 on 2026-01-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_review_service_request_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='payout_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often automatic payouts are processed.', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='flutterwave_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Provider's 80% share of cancellation penalty.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to the requester.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='refund_reason',
            field=models.CharField(blank=True, default='', help_text="Reason for refund (e.g., 'user_cancelled', 'provider_cancelled').", max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('partial', 'Partially Refunded'), ('full', 'Fully Refunded'), ('failed', 'Refund Failed')], default='none', help_text='Status of refund for this booking.', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('instant', 'Instant'), ('manual', 'Manual')], default='weekly', max_length=10),
        ),
        migrations.AlterField(
            model_name='providerpayoutsettings',
            name='payout_weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tuesday'), (3, 'Thursday'), (4, 'Friday')], default=1, help_text='Day of week for weekly payouts. Ignored for monthly.'),
        ),
    ]
