# Generated by Django 6.0 on 2026-01-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_providerpayoutsettings_payout_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='instant_payout_count_this_period',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of instant payouts used in current payout period.'),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='instant_payout_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of current instant payout tracking period.', null=True),
        ),
    ]
