# Generated by Django 6.0 on 2026-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_providerpayoutsettings_instant_payout_count_this_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Reset Code', 'verbose_name_plural': 'Password Reset Codes'},
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address that requested the reset', null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last failed attempt', null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When the code was successfully used', null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='used_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address that used the code', null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='Browser/device info', max_length=500),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(db_index=True, help_text='6-digit numeric reset code', max_length=6),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(help_text='When this code expires'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'code'], name='core_passwo_user_id_488ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'created_at'], name='core_passwo_user_id_53f4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['created_at'], name='core_passwo_created_015adc_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['expires_at'], name='core_passwo_expires_afe7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['used', 'expires_at'], name='core_passwo_used_d7de32_idx'),
        ),
    ]
