# Generated by Django 5.2.10 on 2026-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_passwordresetcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_bank_name',
            field=models.CharField(blank=True, default='', help_text='Human readable bank name (e.g., GCB Bank, Ecobank)', max_length=100),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='flutterwave_mobile_network',
            field=models.CharField(blank=True, default='', help_text='Mobile money network code (e.g., mtn, vodafone, airtel)', max_length=50),
        ),
    ]
