# Generated by Django 5.2.10 on 2026-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_providerpayoutsettings_flutterwave_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location_address',
            field=models.CharField(blank=True, help_text='Human-readable address of the service location', max_length=500, null=True),
        ),
    ]
