# Generated by Django 5.2.10 on 2026-01-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_servicerequest_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingKYCProvider',
            fields=[
            ],
            options={
                'verbose_name': 'Pending KYC Verification',
                'verbose_name_plural': 'Pending KYC Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.serviceprovider',),
        ),
    ]
