# Generated by Django 5.2.10 on 2026-01-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_pendingkycprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='selected_tier',
            field=models.CharField(blank=True, choices=[('budget', 'Budget'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Quality tier selected by user during booking', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProviderCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Licensed Cosmetologist', 'Nail Tech Certificate'", max_length=150)),
                ('issuing_organization', models.CharField(blank=True, help_text='Organization that issued this certification', max_length=150)),
                ('document', models.FileField(blank=True, help_text='Upload certification document (optional)', null=True, upload_to='certifications/%Y/%m/%d/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiration', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified this certification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.serviceprovider')),
            ],
            options={
                'verbose_name': 'Provider Certification',
                'verbose_name_plural': 'Provider Certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
