# Generated by Django 5.2.10 on 2026-01-18 19:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_servicerequest_selected_tier_providercertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requester_average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating received from providers', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requester_review_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reviews received from providers'),
        ),
        migrations.CreateModel(
            name='RequesterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_reviews_given', to='core.serviceprovider')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester_review', to='core.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requester Review',
                'verbose_name_plural': 'Requester Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'service_request')},
            },
        ),
    ]
