# Generated by Django 5.2.10 on 2026-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_customuser_requester_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, default='', help_text='Paystack recipient code used for this transfer.', max_length=64),
        ),
        migrations.AddField(
            model_name='payout',
            name='paystack_reference',
            field=models.CharField(blank=True, default='', help_text='Paystack transfer reference.', max_length=128),
        ),
        migrations.AddField(
            model_name='payout',
            name='paystack_status',
            field=models.CharField(blank=True, default='', help_text='Paystack transfer status.', max_length=32),
        ),
        migrations.AddField(
            model_name='payout',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, default='', help_text='Paystack transfer code.', max_length=64),
        ),
        migrations.AddField(
            model_name='payout',
            name='paystack_transfer_id',
            field=models.CharField(blank=True, default='', help_text='Paystack transfer ID.', max_length=64),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_account_name',
            field=models.CharField(blank=True, default='', help_text='Verified account name from Paystack.', max_length=120),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_account_number',
            field=models.CharField(blank=True, default='', help_text='Bank account number for Paystack payouts.', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_bank_code',
            field=models.CharField(blank=True, default='', help_text='Paystack bank code.', max_length=30),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_bank_name',
            field=models.CharField(blank=True, default='', help_text='Human readable bank name for Paystack.', max_length=100),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_currency',
            field=models.CharField(blank=True, default='', help_text='Currency for Paystack payouts (NGN, GHS, ZAR, KES, XOF).', max_length=10),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, default='', help_text='Paystack transfer recipient code (created via API).', max_length=64),
        ),
        migrations.AddField(
            model_name='providerpayoutsettings',
            name='paystack_recipient_type',
            field=models.CharField(blank=True, default='', help_text='Recipient type: nuban, ghipss, basa, mobile_money.', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_access_code',
            field=models.CharField(blank=True, help_text='Paystack access code for payment page.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_channel',
            field=models.CharField(blank=True, help_text='Paystack payment channel (card, bank, mobile_money, etc.).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Paystack processing fee.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_refund_id',
            field=models.CharField(blank=True, help_text='Paystack refund ID if refunded.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, help_text='Paystack transaction ID.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference for tip payment.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tip_paystack_transaction_id',
            field=models.CharField(blank=True, help_text='Paystack transaction ID for tip payment.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='providerpayoutsettings',
            name='payout_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_gateway',
            field=models.CharField(blank=True, default='', help_text='Payment gateway used for this booking (stripe|flutterwave|paystack).', max_length=20),
        ),
    ]
