# Generated by Django 5.2.10 on 2026-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_payout_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderpricing',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('nails', 'Nail Art'), ('makeup', 'Makeup'), ('facial', 'Facial'), ('waxing', 'Waxing'), ('massage', 'Massage'), ('tattoo', 'Tattoo'), ('styling', 'Hair Styling'), ('treatment', 'Hair Treatment'), ('extensions', 'Hair Extensions'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('braids', 'Braids'), ('shave', 'Shave'), ('color', 'Hair Coloring'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('nails', 'Nail Art'), ('makeup', 'Makeup'), ('facial', 'Facial'), ('waxing', 'Waxing'), ('massage', 'Massage'), ('tattoo', 'Tattoo'), ('styling', 'Hair Styling'), ('treatment', 'Hair Treatment'), ('extensions', 'Hair Extensions'), ('other', 'Other')], default='haircut', max_length=20),
        ),
    ]
