# Generated by Django 5.2.10 on 2026-01-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_serviceproviderpricing_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_mismatch_at_signup',
            field=models.BooleanField(default=False, help_text='True if user selected different country than GPS detected'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='detected_country_at_signup',
            field=models.CharField(blank=True, help_text='Country detected via GPS at signup time', max_length=100, null=True),
        ),
    ]
