# Generated by Django 5.2.10 on 2026-01-25 21:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_customuser_country_mismatch_at_signup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercertification',
            name='document',
            field=models.FileField(blank=True, help_text='Upload certification document (PNG, JPG, JPEG up to 5MB or PDF up to 10MB)', null=True, upload_to='certifications/%Y/%m/%d/', validators=[core.models.validate_certification_file]),
        ),
    ]
