# Generated by Django 5.2.10 on 2026-02-08 07:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for this user', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_credits',
            field=models.PositiveIntegerField(default=0, help_text='Number of discounted bookings remaining from referrals'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referral_credits_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total credits earned from referrals'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referral_credits_used',
            field=models.PositiveIntegerField(default=0, help_text='Total credits used for discounts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0, help_text='Total number of successful referrals'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pre_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before referral discount was applied', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='referral_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual discount amount in booking currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='referral_discount_applied',
            field=models.BooleanField(default=False, help_text='Whether a referral discount was applied to this booking'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='referral_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('7.00'), help_text='Referral discount percentage (default 7%)', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('credits_awarded', models.BooleanField(default=False, help_text='Whether credits have been awarded to referrer')),
                ('credits_amount', models.PositiveIntegerField(default=5, help_text='Number of credits to award when qualified')),
                ('qualified_at', models.DateTimeField(blank=True, help_text='When the referred user completed their first paid booking', null=True)),
                ('qualifying_booking', models.ForeignKey(blank=True, help_text='The booking that qualified this referral', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicerequest')),
                ('referred_user', models.ForeignKey(help_text='User who signed up using the referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who shared their referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
