# Generated by Django 5.2.10 on 2026-02-08 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_customuser_referral_code_customuser_referral_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='credits_amount',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of discount credits awarded (5 per referral)'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='qualified_at',
            field=models.DateTimeField(blank=True, help_text='When the referred user completed their first booking', null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='qualifying_booking',
            field=models.ForeignKey(blank=True, help_text='The first paid booking that qualified this referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_for_referral', to='core.servicerequest'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(help_text='User who signed up using the code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(help_text='User who shared the referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='core_referr_referre_c8a5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user'], name='core_referr_referre_6bec10_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'credits_awarded'], name='core_referr_status_b9d604_idx'),
        ),
    ]
