# Generated by Django 5.2.10 on 2026-02-08 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_referral_credits_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique referral code (format: STYLORIA-username)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_credits',
            field=models.PositiveIntegerField(default=0, help_text='Available discount credits (7% off per credit)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this user during signup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_referral_credits_earned',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime credits earned from referrals'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_referral_credits_used',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime credits used on bookings'),
        ),
    ]
