# Generated by Django 5.2.10 on 2026-02-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='referral_credit_refunded',
            field=models.BooleanField(default=False, help_text='Whether the referral credit was refunded after cancellation'),
        ),
    ]
