# Generated by Django 5.2.10 on 2026-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_servicerequest_referral_credit_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercertification',
            name='certified_service_types',
            field=models.JSONField(blank=True, default=list, help_text="List of service types this certification qualifies for (e.g., ['massage', 'facial'])"),
        ),
    ]
