# Generated by Django 5.2.10 on 2026-02-15 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_providercertification_certified_service_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerportfoliomedia',
            name='file',
            field=models.FileField(max_length=500, upload_to='provider_portfolio/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'm4v', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='providerportfoliomedia',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='provider_portfolio_thumbs/%Y/%m/%d/'),
        ),
    ]
