# Generated by Django 5.2.10 on 2026-04-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_supportthread_rated_at_supportthread_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='new_user_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual new user discount amount in booking currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='new_user_discount_applied',
            field=models.BooleanField(default=False, help_text='Whether a new user promo discount was applied to this booking'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='new_user_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='New user discount percentage applied (default 5%)', max_digits=5, null=True),
        ),
    ]
